# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wasted', '0003_friendlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('deadline', models.DateTimeField()),
                ('timePerDay', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasted.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasted.Person')),
            ],
        ),
    ]
