# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wasted', '0004_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateField(auto_now=True)),
                ('endTime', models.DateField()),
                ('position', models.CharField(max_length=128)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasted.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasted.Person')),
            ],
        ),
    ]
