# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 11:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasted', '0006_auto_20170923_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedactivity',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 23, 11, 52, 10, 395405)),
        ),
    ]
